import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./provider";
import { Outfit } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import Header from "./_components/Header";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "AI Note Taker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <ConvexClientProvider>
            {children}
            </ConvexClientProvider>
            <Toaster richColors/>
        </body>
      </html>
    </ClerkProvider>
  );
}
